### ISSUE TITLE
"standard vams file created" madness (race condition?)

### ISSUE THREAD

**Issue by felix-salfelder** [Qucs/qucs#474] opened 2016-02-14 18:12 UTC
here i tried to do "make distcheck -j3".

https://travis-ci.org/Qucs/qucs/jobs/109191292 

it fails. i suspect a race condition, we should use existing header files....(?)

**Comment by guitorri** [comment] 2016-11-03 21:54
Duplicate of #545.

**Closed by guitorri** 2016-11-03 21:54 UTC
