### ISSUE TITLE
transient simulation sometimes takes too long

### ISSUE THREAD

**Issue by bergmannm** [Qucs/qucs#698] opened 2017-07-17 07:24 UTC
Hi,
I'm trying to simulate negative rail generation of http://www.electronics-lab.com/project/0-30-vdc-stabilized-power-supply-with-current-control-0-002-3-a/ .  I've uploaded simulated circuit at 
http://imgur.com/a/NX7pX    and https://pastebin.com/wHpnzW1X . The problem is that simulation time depends quite a bit  on selected values. I've tried to change value of R6, all other settings remained the same.

With R6=500 Ohm -> less than a second
With R6=300 Ohm  -> about 5 seconds
With R6=400 Ohm  -> simulation was not finished even after 5 minutes.

Is there a way to speed up simulations ?

I'm using qucs version 0.0.19 .

**Comment by ra3xdh** [comment] 2017-07-17 07:31
Are you using Qucsator? Yes, it is well known bug. Qucsator may hang when some component goes into switch mode. See also #41. Qucsator is more suitable for RF circuits simulation in frequency domain. There was some attempts to fix its performance in time domain. 

Use SPICE simulation kernels to simulate such circuits. My Qucs-S + Ngspice can give a good result. See https://ra3xdh.github.io/ for more details. I hope, we will see Qucs-S and Qucs merged in the next year. You may also like experimental Ngspice support in KiCAD.

**Comment by ra3xdh** [comment] 2017-07-17 07:32
Closed as duplicate of #41.

**Closed by ra3xdh** 2017-07-17 07:32 UTC

**Comment by felix-salfelder** [comment] 2017-07-17 07:56
for completeness, let me add that there is gnucsator and that it provides a qucsator drop in replacement.
gnucsator is gnucap based and implements a real ("post-spice") transient solver.

unfortunately, some of the components are still missing, and only transient simulation is wrapped.
native gnucap support will be available as soon as we have modular simulator drivers for qucs.

**Comment by ombra32** [comment] 2021-05-29 16:32
I'm having the same issue 4 years later with Qucs 0.0.20 on Ubuntu 20.04.
In a simple AC generator and R divider circuit, the simulation is stuck at 0%.
I can't use Qucs-s because in another circuit I need a triac and Qucs-s lacks of some non linear components (see the related [issue](https://github.com/ra3xdh/qucs_s/issues/63)).

![divider](https://user-images.githubusercontent.com/75046586/120077757-3ae62000-c0ac-11eb-9b24-b53197e500e2.png)

**Comment by ra3xdh** [comment] 2021-05-29 16:40
What is the frequency of the AC source? Looks like you have accidentally left the default value 1GHz unchanged. In such case the simulation with qucsator will stuck.

**Comment by ombra32** [comment] 2021-05-29 20:35
> What is the frequency of the AC source? Looks like you have accidentally left the default value 1GHz unchanged. In such case the simulation with qucsator will stuck.

You are right! Congratulations!
I'm very sorry, I'm new to Qucs.
Maybe having the AC source frequency set to 50Hz by default, like some other circuit simulators do, can help beginners and save developers from boring answers..

Regards,
Marco

**Comment by Rmano** [comment] 2021-05-31 07:25
Well, 100 ms at 1 GHz is *quite a lot* of periods to be simulated... maybe it's not stuck ;-).

**Comment by ombra32** [comment] 2021-06-02 13:05
I'm stuck in another circuit now: a full diode bridge with an AC source and a time controlled switch.
As you stated, Qucsator seems not so good for switching simulations, but time controlled switch is not present in Qucs-s.

![bridge](https://user-images.githubusercontent.com/75046586/120484874-c95fe780-c3b3-11eb-8cf4-935dfd9a3adf.png)

**Comment by ra3xdh** [comment] 2021-06-02 13:07
You may use the relay instance controlled by rectangular pulse source. This device is available for Qucs-S and SPICE-compatible.

**Comment by Rmano** [comment] 2021-06-02 13:50
@ombra32  it would be useful if you could share the `.SCH` file (you can zip it and drop it into an issue here) so that we could check...

**Comment by ombra32** [comment] 2021-06-02 13:57
> @ombra32 it would be useful if you could share the `.SCH` file (you can zip it and drop it into an issue here) so that we could check...

No problem, it's a very basic circuit
[dimmerID.zip](https://github.com/Qucs/qucs/files/6585015/dimmerID.zip)

**Comment by Rmano** [comment] 2021-06-02 14:05
Well, I received errors about Ron and Roff with your circuit --- those are critical parameters for the convergence of the simulation...
After tweaking them a bit, I have this (run time around 3 seconds):

![image](https://user-images.githubusercontent.com/6414907/120494748-5e66de80-c3bc-11eb-916b-597a165ea266.png)

When S1 is open, the left-hand circuit is floating around, and that can be a problem for the simulator. Anyway, I have no idea if the result is the expected one (no time to think a lot now ;-))

**Comment by ombra32** [comment] 2021-06-02 14:59
> Well, I received errors about Ron and Roff with your circuit --- those are critical parameters for the convergence of the simulation...

Many thanks Romano.
How can I receive this errors too? Is there an advanced log or simulation mode to enable?

**Comment by Rmano** [comment] 2021-06-02 15:01
> Many thanks Romano.
> How can I receive this errors too? Is there an advanced log or simulation mode to enable?

No, they were just in the simulation windows. Which version are you using? Mine is this one 0.0.20-rc2 (the appexec thingy I made)

**Comment by ombra32** [comment] 2021-06-02 15:10
Qucs 0.0.20.201022-2 from launchpad repo on Ubuntu 20.04
simulation stucks as my previous image without messages

![qv](https://user-images.githubusercontent.com/75046586/120505602-69723c80-c3c5-11eb-9aed-4f663a64ba11.png)

**Comment by Rmano** [comment] 2021-06-02 15:15
...no idea, I didn't even know there was a working repo for 20.04. The project is in bad need of C++ developers to port it from Qt4 to Qt5-6 (I would like to be able to help, and the existing developers are doing all that they can!), and the version I packed is from June 2020...

See here: https://github.com/Qucs/qucs/issues/1006#issuecomment-643792968 and here:  https://rmano.github.io/qucsAppImagesBuild/  --- but no guarantees at all, it is just a stop-gap for now.

**Comment by ombra32** [comment] 2021-06-02 15:22
> ...no idea, I didn't even know there was a working repo for 20.04. The project is in bad need of C++ developers to port it from Qt4 to Qt5-6 (I would like to be able to help, and the existing developers are doing all that they can!), and the version I packed is from June 2020...

I've installed from here:
[http://qucs.sourceforge.net/install.html#install_ubuntu](http://qucs.sourceforge.net/install.html#install_ubuntu)
I think is the same for all Ubuntu versions

> See here: [#1006 (comment)](https://github.com/Qucs/qucs/issues/1006#issuecomment-643792968) and here: https://rmano.github.io/qucsAppImagesBuild/ --- but no guarantees at all, it is just a stop-gap for now.

Ok, I'll give a try..many thanks!

**Comment by Rmano** [comment] 2021-06-02 15:35
> Ok, I'll give a try..many thanks!

Well, the PPA seems more recent. I really don't know, you can just try. But does it work with my modifications to Ron and R0ff? If so, I do not think it's a big problem. Ron and Roff of switches are a PITA for every simulator...

**Comment by ombra32** [comment] 2021-06-03 06:00
With qucs appimage 0.0.20-rc2 I get the message you mentioned, but with 0.0.20 version from PPA still no message.

![warn](https://user-images.githubusercontent.com/75046586/120594223-ed1d3f00-c440-11eb-9390-a032a1270b8a.png)

> But does it work with my modifications to Ron and R0ff? If so, I do not think it's a big problem. Ron and Roff of switches are a PITA for every simulator...

 Yes, changing Roff only, it works with both versions.
